In [51]:
class MYLR:
    
    def __init__(self):
        self.m = None
        self.b = None
        
    def fit(self,X_train,y_train):
        
        num = 0
        den = 0
        
        for i in range(X_train.shape[0]):
            
            num = num + ((X_train[i] - X_train.mean())*(y_train[i] - y_train.mean()))
            den = den + ((X_train[i] - X_train.mean())*(X_train[i] - X_train.mean()))
        
        self.m = num/den
        self.b = y_train.mean() - (self.m * X_train.mean())
        print(self.m)
        print(self.b)       
    
    def predict(self,X_test):
        
        print(X_test)
        
        return self.m * X_test + self.b

In [52]:
import numpy as np 
import pandas as pd 

In [53]:
df = pd.read_csv('updated_placement.csv')

In [54]:
df.head()

cgpa    package
0  9.75  68.493428
1  5.36  23.323471
2  5.65  27.795377
3  5.60  29.046060
4  6.48  34.331693

In [55]:
X = df.iloc[:,0].values
y = df.iloc[:,1].values

In [56]:
X

array([9.75, 5.36, 5.65, 5.6 , 6.48, 9.09, 8.59, 9.57, 6.53, 8.96, 6.09,
       8.3 , 9.89, 5.26, 6.1 , 7.84, 5.55, 9.31, 9.14, 9.86, 6.09, 6.64,
       9.81, 8.78, 8.36, 6.93, 6.94, 8.38, 8.71, 7.01, 7.4 , 7.74, 8.96,
       6.04, 8.86, 6.26, 7.59, 5.26, 7.91, 6.09, 6.12, 7.64, 9.35, 6.13,
       5.44, 9.68, 8.2 , 5.3 , 7.35, 6.23, 8.22, 7.48, 8.4 , 9.46, 9.27,
       8.31, 6.09, 5.66, 9.45, 5.22, 6.47, 9.21, 5.75, 5.24, 7.19, 5.77,
       7.37, 7.01, 6.98, 6.32, 7.21, 5.97, 6.95, 7.81, 7.13, 6.4 , 9.7 ,
       7.81, 6.63, 7.34, 9.97, 7.83, 8.15, 6.6 , 7.42, 5.17, 7.36, 9.65,
       7.44, 5.01, 5.18, 5.29, 8.46, 5.81, 5.91, 9.39, 9.6 , 8.66, 9.54,
       8.52, 9.25, 5.63, 8.57, 5.25, 5.29, 8.15, 5.81, 9.43, 8.81, 5.72,
       6.89, 9.03, 8.42, 5.56, 8.32, 5.43, 5.13, 7.24, 5.79, 9.7 , 7.  ,
       6.04, 9.05, 7.9 , 8.56, 6.52, 5.66, 7.35, 6.51, 6.66, 7.58, 6.18,
       5.24, 6.79, 9.85, 6.44, 7.48, 5.82, 5.87, 6.41, 9.26, 7.86, 5.56,
       6.96, 6.  , 8.39, 9.4 , 7.25, 7.4 , 8.59, 5.

In [57]:
y

array([68.49342831, 23.3234714 , 27.79537708, 29.04605971, 34.33169325,
       60.43172609, 59.05842563, 67.23486946, 34.36105123, 60.68512009,
       29.97316461, 52.06854049, 69.38392454, 18.77343951, 27.55016433,
       47.27542494, 23.47433776, 81.1125542 , 59.58395185, 65.7753926 ,
       33.83129754, 35.9484474 , 68.23505641, 54.95050363, 52.51123455,
       39.52184518, 37.09801285, 54.55139604, 55.89872262, 39.5166125 ,
       42.79658678, 51.10455637, 59.57300555, 28.28457814, 60.24508982,
       30.1583127 , 46.31772719, 18.68065975, 46.4436279 , 31.29372247,
       32.67693316, 46.74273656, 63.26870344, 30.69779261, 21.44295602,
       65.36031158, 51.07872246, 25.11424445, 44.18723658, 28.77391969,
       52.84816794, 44.02983544, 52.646156  , 65.82335258, 64.76199904,
       54.96256024, 29.22156495, 25.98157525, 65.16252686, 24.15109025,
       33.74165152, 61.72868205, 25.28733005, 20.00758675, 43.52505164,
       30.41248006, 43.55597976, 42.1070658 , 40.52327205, 31.90

In [58]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [59]:
X_train.shape

(160,)

In [60]:
lr = MYLR()

In [61]:
y_train

array([27.55587697, 26.05863536, 60.24697225, 46.19629787, 27.05110817,
       51.21428551, 46.74273656, 42.69867314, 63.05491987, 60.43172609,
       63.31310722, 59.66925852, 52.06854049, 24.55434217, 52.51123455,
       21.12653487, 43.55597976, 34.36105123, 58.14579658, 35.2543665 ,
       55.89872262, 38.84718486, 28.31578369, 63.26870344, 42.69252767,
       54.45578809, 46.95307443, 31.8723718 , 58.61510078, 39.96926772,
       55.7513347 , 45.84412032, 61.52609858, 64.17057711, 23.3234714 ,
       68.50386607, 37.62818749, 56.49396935, 23.55063666, 37.90641256,
       39.85908677, 46.31772719, 33.16837943, 53.24033833, 25.28733005,
       68.49342831, 54.55139604, 33.64766584, 65.41022691, 30.18564563,
       33.83129754, 50.21739301, 65.33154902, 22.38503353, 47.5019853 ,
       42.79658678, 69.58614495, 81.1125542 , 24.15109025, 25.88568489,
       52.81527807, 42.36740454, 31.63827137, 44.01279759, 27.44467571,
       64.39289642, 35.9484474 , 54.96256024, 23.47433776, 67.23

In [62]:
lr.fit(X_train,y_train)

10.114368627620584
-30.45149800343502


In [63]:
X_train.shape[0]

160

In [64]:
X_train[0]

5.82

In [65]:

X_train.mean()

7.461562499999999

In [66]:
X_test[0]

8.42

In [67]:
print(lr.predict(X_test[0]))

8.42
54.7114858411303
